@startmindmap
title <b>数据库</b>
* 关系型数据库
** 架构
** 索引
*** B-Tree
**** 根节点至少包含两个孩子
**** 树中每个节点最多含有m个孩子 (m>=2)
**** 除根节点和叶节点外，其他节点至少有ceil(m/2)个孩子
**** 所有叶子节点都位于同一层
**** 最后一个条件分为三个小条件(自查)
*** B+-Tree
**** 非叶子节点的子树指针与关键字个数相同
**** 非叶子节点的子树指针P[i],指向关键字值[K[i],K[1])非叶子节点的子树
**** 非叶子节点仅用来索引,数据都保存在叶子节点中
**** 所有叶子节点均有一个链指针指向下一个叶子结点
*** B+-Tree更适合用来做存储索引
**** B+树的磁盘读写代价更低
**** B+树的查询效率更加稳定
**** B+树更有利于对数据库的扫描


** 锁
** 语法
** 理论范式

@endmindmap